### ISSUE TITLE
AWS::ApiGateway.AccessLogSetting.DestinationArn AllowedPatternRegex

### ISSUE THREAD

**Issue by jlhood** [aws-cloudformation/cfn-lint#1160]
*Description of issue.*

Amazon API Gateway [just announced](https://aws.amazon.com/about-aws/whats-new/2019/10/amazon-api-gateway-now-supports-access-logging-to-amazon-kinesis-data-firehose/) support for writing Access Logs directly to Kinesis Data Firehose instead of CloudWatch Logs.

Buried in the CloudFormation documentation is [this constraint](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-apigateway-deployment-accesslogsetting.html#cfn-apigateway-deployment-accesslogsetting-destinationarn):

> DestinationArn
>   The Amazon Resource Name (ARN) of the CloudWatch Logs log group or Kinesis Data Firehose delivery stream to receive access logs. If you specify a Kinesis Data Firehose delivery stream, the stream name must begin with amazon-apigateway-.

The stream name prefix constraint is likely going to trip up customers who are letting CloudFormation name their Kinesis Data Firehose delivery stream since it won't have the required prefix unless their stack name begins with amazon-apigateway-.

Opening this issue to see if cfn-lint could help users by detecting this scenario and issuing a warning/error.

**Comment by PatMyron** [comment]
As described [here](https://github.com/aws-cloudformation/cfn-python-lint/issues/903#issuecomment-595356853), this would need an `AllowedPatternRegex` to be enforced:

https://github.com/aws-cloudformation/cfn-python-lint/blob/a46773c752247c51effef415bd3462eaec10ab0b/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json#L33-L36
