### ISSUE TITLE
AWS::Serverless::Application parameters

### ISSUE THREAD

**Issue by redbaron09** [aws-cloudformation/cfn-lint#1194]
*Description of issue.*
When creating a `AWS::Serverless::Application` input parameters should match parameters required in the nested template.

  * Supplying parameters to `AWS::Serverless::Application` resources that do not exist in the child template will succeed in creating a Change Set but fail upon deployment.
 * Neglecting to provide parameters `AWS::Serverless::Application` resources that do exist in the child template will fail in creating a Change Set.

**Comment by kddejong** [comment]
@redbaron09 agreed here.  We have tried not to reach out to validate things in an AWS account.   

Is there a way to do this without actually querying the account?

Or maybe we need to start thinking about a way to query live accounts when requested.

**Comment by redbaron09** [comment]
Following `Location` on the local file system, reading the parameters section, and comparing against the parameters supplied in the parent stack would be sufficient.
I'm using `AWS::Serverless::Application` in place of `AWS::CloudFormation::Stack`.

**Comment by kddejong** [comment]
We are doing this for `AWS::CloudFormation::Stack` with rule [E3043](https://github.com/aws-cloudformation/cfn-lint/blob/3492649d613a61fff3063ce0ffa404e1055c6a3a/src/cfnlint/rules/resources/cloudformation/NestedStackParameters.py).   Need to update the transform logic to leave strings as is.
