### ISSUE TITLE
EOL Python 3.4 and 2.7

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#1291]
*Description of issue.*
Python 3.4 is EOL.   This is to track the work to remove support for python 3.4

**Comment by kddejong** [comment]
pyyaml has dropped support for Python 3.4 as of version of 5.3

**Comment by gliptak** [comment]
https://devguide.python.org/#status-of-python-branches

@kddejong  are you open to a PR removing ```Python 2.7``` and ```Python 3.4```?

**Comment by PatMyron** [comment]
Python 2.7 usage is decreasing but still unfortunately holds ~5% of downloads:
https://pypistats.org/packages/cfn-lint

Python 3.4 usage is already minimal and the upgrade to 3.5 is less significant, so we should be able to easily deprecate it this summer

**Comment by PatMyron** [comment]
@kddejong think this issue can be closed: https://github.com/aws-cloudformation/cfn-lint/pull/2347
