### ISSUE TITLE
New rule for when ZipFile can be used based on Runtime

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#1439]
New rule for Lambda Function.

`ZipFile` can only be used when `Runtime` is set to either of nodejs8.10, nodejs10.x, nodejs12.x, python2.7, python3.6, python3.7.

**Comment by PatMyron** [comment]
[I think this one should be fixed in CloudFormation itself](https://github.com/aws-cloudformation/aws-cloudformation-coverage-roadmap/issues/80#issuecomment-604138808)

**Comment by kddejong** [comment]
I think that is okay.  Do you think that would ever cover all languages?  I'm not sure ZipFile would  work with Go for example.

**Comment by kddejong** [comment]
Another issue `Invalid request provided: Using the ZipFile attribute requires a runtime to be specified`

**Comment by kddejong** [comment]
Fixed with #2676
