### ISSUE TITLE
E0001 Error transforming template: Unable to parse config file: C:\Users\[user]/.aws/config

### ISSUE THREAD

**Issue by fabioaraujopt** [aws-cloudformation/cfn-lint#1478]
*cfn-lint version: (`0.29.5`)*

*Description of issue.*

I have cfn-lint installed, and tried to run:
 `cfn-lint template.yaml`

It prompts the error:
`E0001 Error transforming template: Unable to parse config file: C:\Users\fuj/.aws/config
template.yaml:1:1`

The specified file ` C:\Users\fuj/.aws/config` have the following content:
```
[default]
region = eu-central-1
output = json

[profile XXXXXX]
    output=json
    region = eu-central-1
    role_arn = arn:aws:iam::XXXXXXXX:role/XXXXX
    mfa_serial = arn:aws:iam::XXXXXXXX:mfa/XXXXX
    source_profile = default
```

**Comment by kddejong** [comment]
Interesting.  I'll have to test a few things out there.  We don't require a config file but it looks like the SAM translator does.  I'm assuming this template is a SAM template?

**Comment by kddejong** [comment]
No response and no other reports.  Closing this for now and we can re-open as needed.
