### ISSUE TITLE
Parameter Not Used reported, although its being used in an Assertion Rule

### ISSUE THREAD

**Issue by tekdj7** [aws-cloudformation/cfn-lint#1882]
*cfn-lint version: (`cfn-lint --version`)*
0.44.5 (also already ran, `cfn-lint -u`)

*Description of issue.*
Using the AWS Quick Start [ad-2.template](https://github.com/aws-quickstart/quickstart-microsoft-activedirectory/blob/main/templates/ad-2.template), cfn-lint is reporting `VPCID Parameter not used`.  Although it's actually being used in the `SubnetsInVPC` rule.

**Comment by kddejong** [comment]
We currently don't have a lot of logic around the rules section.  We will need to build that out so we can handle this scenario.

**Comment by kddejong** [comment]
This issue is no longer appearing
