### ISSUE TITLE
Support for Wavelength Zones as valid Availability Zones attributes

### ISSUE THREAD

**Issue by rhbelson** [aws-cloudformation/cfn-lint#1966]
*cfn-lint version: (`cfn-lint --version`)* Latest (v0.48.1)

*Description of issue.* When creating CloudFormation template for resources in a Wavelength Zones, I get a warning `"You must specify a valid allowed value for [Attribute] (us-west-2-wl1-sea-wlz-1). Valid values are ["af-south-1a","af-south-1b"....]"`

I'm requesting support that the full list of Wavelength Zones be added to the list of valid availability zones, which are:

- us-east-1-wl-bos-wlz-1
- us-east-1-wl-nyc-wlz-1
- us-east-1-wl-was-wlz-1
- us-east-1-wl-atl-wlz-1
- us-east-1-wl-mia-wlz-1
- us-east-1-wl-dfw-wlz-1
- us-west-2-wl-sfo-wlz-1
- us-west-2-wl-las-wlz-1
- us-west-2-wl-den-wlz-1
- us-west-2-wl-sea-wlz-1
- ap-northeast-1-wl1-nrt-wlz-1
- ap-northeast-2-wl1-cjj-wlz-1
- ap-northeast-1-wl1-kix-wlz-1

**Comment by PatMyron** [comment]
list being sourced from https://github.com/aws-cloudformation/cfn-python-lint/blob/master/src/cfnlint/data/ExtendedSpecs/all/03_value_types.json

Available Wavelength zones are probably going to be too frequently updated to manually maintain. **Which property type?**

**Comment by rhbelson** [comment]
Who maintains 03_value_types.json? Just wanted to make sure available Wavelength Zones were matched to the available Local Zones, which also expects to change throughout the year. 

In terms of property type, this would be the **AvailabilityZone** attribute for a subnet resource -- is this what you had in mind?
