### ISSUE TITLE
E7003 now throws an error on CFN-acceptable Mapping Keys.

### ISSUE THREAD

**Issue by jonathanmorley** [aws-cloudformation/cfn-lint#2014]
*cfn-lint version: 0.49.2*

*Description of issue.*

cfn-lint throws E7003 against the following snippet:

```
Mappings:
  AccountMap:
    "Fn::Transform":
      Name: "AWS::Include"
      Parameters:
        Location:
          Fn::Sub: "s3://foo-${AWS::Region}/accounts.yaml"
```

`s3://foo-${AWS::Region}/accounts.yaml` looks like

```
"012345678910":
  AccountName: foo
"012345678911":
  AccountName: bar
```

probably because of the `:`s in `Fn::Transform` that are being treated literally.

**Comment by PatMyron** [comment]
While this specifically changed in https://github.com/aws-cloudformation/cfn-lint/pull/2006, this still generally feels like a subset of https://github.com/aws-cloudformation/cfn-lint/issues/476
