### ISSUE TITLE
Add EXISTS to concise rule as an Operator

### ISSUE THREAD

**Issue by nathanagood** [aws-cloudformation/cfn-lint#2024]
## Affects version 

.49.2+

## Description of issue

**Feature request**: add "EXISTS" an available operator for the concise rules in the TXT file. Example rule might look something like:

```
AWS::S3::Bucket BucketEncryption EXISTS ERROR S3 bucket must include encryption configuration
```

**Comment by kftsehk** [comment]
#2656 should solve your issue

**Comment by kddejong** [comment]
Will be in the next release.
