### ISSUE TITLE
[Feature Request] NPM package

### ISSUE THREAD

**Issue by josefaidt** [aws-cloudformation/cfn-lint#2053]
*Description of issue.*

Existing community NPM package `cfn-lint` is not actively maintained and up-to-date. Requesting this package be published to npm for use in Node.js modules and packages such as https://github.com/aws-amplify/amplify-cli

**Comment by PatMyron** [comment]
NPM package was a separate project:
https://github.com/martysweet/cfn-lint
This project is written in Python and probably cannot directly interface with JavaScript/NPM as easily

You could probably call this CLI in JavaScript code if desired though

**Comment by josefaidt** [comment]
That package is in use right now but it appears to be out-of-date and not actively maintained. Is that package the official js distribution?

**Comment by PatMyron** [comment]
Despite the same name, the two projects are not related, this section in their README explains a bit more:
https://github.com/martysweet/cfn-lint#depreciationretirement-notice
