### ISSUE TITLE
cfn-lint fails with Sub for RedshiftCluster

### ISSUE THREAD

**Issue by Gwynbleidd017** [aws-cloudformation/cfn-lint#2058]
*cfn-lint version: 0.44.3

*Description of issue.*
cfn-lint fails in handling some subs.
E1019 Parameter RedshiftCluster.Endpoint.Address for Fn::Sub not found at Outputs/RedshiftHost/Value/Fn::Sub
Sample template: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-redshift.html

Please provide as much information as possible:
Sample CF template : 
`https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/quickref-redshift.html`

Test:
```
cfn-lint -u 
cfn-lint <template>
```

Output for the above template:
```
E1019 Parameter RedshiftCluster.Endpoint.Address for Fn::Sub not found at Outputs/ClusterEndpoint/Value/Fn::Sub
ex.yml:158:5
E1019 Parameter RedshiftCluster.Endpoint.Port for Fn::Sub not found at Outputs/ClusterEndpoint/Value/Fn::Sub
ex.yml:158:5
```
The above worked last week. It fails with updated CloudFormation Specs.

**Comment by kddejong** [comment]
Those attributes got dropped from the [CloudFormation spec](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html).  Its also why I'm hesitating on doing a release with the most recent version.  Talked to some internal teams that are working to address this issue so we can get it resolved and move forward.

**Comment by Gwynbleidd017** [comment]
Yes, I realised Cloudformation dropped those attributes from the spec. I will close this issue.

**Comment by Gwynbleidd017** [comment]
Not an issue with cfn-lint. The attributes were dropped from the cloudformation specs.

**Comment by kddejong** [comment]
Thanks working on getting them added back in.  Hopefully we this weeks release will have them in there again.
