### ISSUE TITLE
E3002 Invalid Property Resources/RESTAPI/Properties/Mode

### ISSUE THREAD

**Issue by Slooz** [aws-cloudformation/cfn-lint#2073]
*cfn-lint version: 0.52.0*

[`AWS::ApiGateway::RestApi.Mode`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-mode) is a valid property, but cfn-lint shows an error:
> E3002 Invalid Property Resources/RESTAPI/Properties/Mode

This is similar to #1219, but this property was [released on April 15, 2021](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html#ReleaseHistory), so it doesn't just look like the [AWS CloudFormation resource specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) is lagging, but that the property was completely forgotten to be added.

**Comment by kddejong** [comment]
@PatMyron any thoughts on this?  We've been fortunate to not have to patch much in lately but the fact that we haven't seen this one in the spec yet has me a little concerned.

**Comment by PatMyron** [comment]
I've asked the team if it's possible to get this fixed in this week's release

**Comment by Slooz** [comment]
[`AWS::ApiGateway::RestApi.Mode`](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-mode) has been added to the spec

**Comment by kddejong** [comment]
#2066 will be the PR for getting it into cfn-lint
