### ISSUE TITLE
cfn-lint does not validate maximum length of RoleName, TopicName, QueueName,...

### ISSUE THREAD

**Issue by luchees** [aws-cloudformation/cfn-lint#2080]
*cfn-lint version: 0.52.0

Several services like Lambda, SNS, SQS,.. are not being validated with the maximum length limit for names.
I am using CDK to generate cloudformation and we are sporadically having issues when deploying names that have too much characters.

I would be able to implement this feature. 
I have created several rules that implement above. Just need to make sure I follow the requested format and need to create PR.

**Comment by PatMyron** [comment]
Have some [concise constraint formats](https://github.com/aws-cloudformation/cfn-python-lint/issues/903#issuecomment-595356853) that handle template syntax edge cases like [dynamic references](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/dynamic-references.html), [intrinsic functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference.html), etc
