### ISSUE TITLE
E3002 for "invalid" property CopyTagsToSnapshot in db Cluster

### ISSUE THREAD

**Issue by luchees** [aws-cloudformation/cfn-lint#2086]
cfn-lint version: cfn-lint 0.52.0

Description of issue.

When updating to newest aws-cdk 1.115 we have an issue when validating the cloudformation.

` E3002 Invalid Property Resources/DBCluster/Properties/CopyTagsToSnapshot `

Recently this property got added in cloudformation and now cdk also added that property.

Solved it for now by using **Metadata** `ignore_check: ['E3002']`

Will try to make PR for this one.

**Comment by PatMyron** [comment]
released recently: https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/238
automatically picked up in https://github.com/aws-cloudformation/cfn-lint/pull/2066#discussion_r675293305, so merging that PR should fix this

---

In the meantime, `cfn-lint --update-specs` / `cfn-lint -u` should pick that up before that gets released
