### ISSUE TITLE
False positive finding

### ISSUE THREAD

**Issue by Alex-at-Amazon** [aws-cloudformation/cfn-lint#2092]
Version  1.9.7

Finding:
-     1 crit
-     Resource: Resources > App001ConnectRole > Properties > Description
-     Message: Description is not a valid property of AWS::IAM::Role
-     Documentation: http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-iam-role.html
-     Which is generating:    Template invalid!

Per the documentation listed from cfn-lint
    Description is a valid Property

This check is creating a false positive.

CFT as LOG file
[CFN-Lint-false-positive-4-IAM-Policy-n-Role-CFT.LOG](https://github.com/aws-cloudformation/cfn-lint/files/6909641/CFN-Lint-false-positive-4-IAM-Policy-n-Role-CFT.LOG)

**Comment by kddejong** [comment]
I think you are referring to https://www.npmjs.com/package/cfn-lint not cfn-lint inside this repository.  I cannot replicate this issue with this version of cfn-lint.

**Comment by kddejong** [comment]
I'll reopen this one if I need to but I believe this issue is from using the nodejs version of cfn-lint not the python version.
