### ISSUE TITLE
Support for python 3.9 runtime in Lambda

### ISSUE THREAD

**Issue by obobrova** [aws-cloudformation/cfn-lint#2102]
*cfn-lint version: (`0.53.0`)*

*Description of issue.*

Amazon has announced that it now supports python3.9 as a runtime for Lambda: https://aws.amazon.com/blogs/compute/python-3-9-runtime-now-available-in-aws-lambda/ `cfn-lint` fails the `E3030` check.

**Comment by PatMyron** [comment]
will be picked up in https://github.com/aws-cloudformation/cfn-lint/issues/2095

**Comment by chenrui333** [comment]
yeah, `cfn-lint -u` solved my issue with `python3.9` running lint error, but it is really costly to run that command. It bumped the cfn-lint run from 4s to 3mins.

When we should we expect the specs goes to the latest release? Thanks!

**Comment by kddejong** [comment]
Should be in the latest release.  Thanks for reporting the issue and with your patience.
