### ISSUE TITLE
Potential performance improvement

### ISSUE THREAD

**Issue by larryboymi** [aws-cloudformation/cfn-lint#2115]
https://github.com/aws-cloudformation/cfn-lint/blob/46cbec6be520f898cc8f98e2eaad9221483fa75a/src/cfnlint/decode/cfn_json.py#L503

I don't have the time to make/test this change in your project, but I was working with the team over at Bridgecrew.io's [checkov](https://github.com/bridgecrewio/checkov) project and identified a potential [performance improvement](https://github.com/bridgecrewio/checkov/issues/1585) for them, where it was using a function like yours above.

If you're interested, the fix I proposed is [here](https://github.com/bridgecrewio/checkov/pull/1596).

Thanks!

**Comment by kddejong** [comment]
@noahjohnhay and @larryboymi thank you.  I think this is all merged in and published.
