### ISSUE TITLE
cfn-lint does not show logging if -f flag is used

### ISSUE THREAD

**Issue by Zirkonium88** [aws-cloudformation/cfn-lint#2125]
cfn-lint 0.54.2

*Description of issue.*

We are using cfn-lint as preventive control within *AWS CodeBuild* and *GitLab*. We would like to collect the linting results via junit. This is possible via flag  `-f junit > ./tests/report.xml`. If no error occur, we can continue with `exit code 0`. If a errors occur, we are able to see any logging. Unfortunenately, *AWS CodeBuild* and *GitLab* directly abort the run, if an exit code unequal zero occur.

* Expected behavior*

In the case you are not using -f flag you diretly seen the root cause of the errors. It would be great to have the same logging behavior with -f flag set. Otherwise debugging (i.e. looking into the test jab of both services) can be tricky.

**Comment by kddejong** [comment]
@Zirkonium88 are you saying you always want an exit code of 0?  how would you determine errors for determining if the job failed?  We have a request for doing an exit code of non zero only on errors.  Which would show warnings and information rules but not sure that is the same ask.

https://github.com/aws-cloudformation/cfn-lint/issues/1586#issuecomment-1286419486

**Comment by PatMyron** [comment]
Can also generally workaround with [`|| true`](https://stackoverflow.com/questions/11231937/bash-ignoring-error-for-a-particular-command):

https://github.com/infracost/infracost/issues/1478#issuecomment-1074207940

**Comment by kddejong** [comment]
created #2346 to help move this logic into cfn-lint

**Comment by kddejong** [comment]
Configuring exit codes now exists in v0.90.0
