### ISSUE TITLE
Architectures property on Lambda function

### ISSUE THREAD

**Issue by roelvandenbranddvc** [aws-cloudformation/cfn-lint#2146]
*cfn-lint version: 0.54.2

Description of issue.

Whilst linting SAM Templates:

Template: 
_MyFunctionResourceName:
        Type: AWS::Serverless::Function
        Properties:
            Architectures: 
              - arm64_

cfn-lint output:
_2021-10-19 08:49:26,867 - cfnlint - INFO - SAM Translator: 1.39.0
2021-10-19 08:49:26,868 - cfnlint - INFO - Setting AWS_DEFAULT_REGION to us-east-1
2021-10-19 08:49:26,933 - cfnlint - INFO - Transformed template:
"Resources": {
    "MyFunctionResourceName": {
      "Properties": {
        "Architectures": [
          "arm64"
        ],_
(continues ofcourse)

Output in build steps:
Verify Yml Start

------------------------------------------------------------------------------------------------------------------------
More info on error codes https://github.com/aws-cloudformation/cfn-lint
E3002 Invalid Property Resources/MyFunctionResourceName/Properties/Architectures
template.yml:84:5

https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-architectures

_Type: AWS::Serverless::Function
Properties:
  Architectures: List_

I would expect the Architectures property would be valid.

**Comment by kddejong** [comment]
Release https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.54.3 will have this
