### ISSUE TITLE
Unknown warning about unpublished metrics

### ISSUE THREAD

**Issue by amancevice** [aws-cloudformation/cfn-lint#2167]
*cfn-lint version: 0.55.0*

*Description of issue.*

`cfn-lint template.yaml` is outputting `There are unpublished metrics. Please make sure you call publish after you record all metrics.` where previous versions of `cfn-lint` did not. This is causing the Atom plugin to display a really intrusive error message on every save event.

Frustratingly, I can't find any information on what this message means

**Comment by PatMyron** [comment]
Could you try forcibly reinstalling and see if that helps?
[`pip3 install --upgrade --force-reinstall cfn-lint`](https://stackoverflow.com/questions/19548957/can-i-force-pip-to-reinstall-the-current-version)

**Comment by yudao** [comment]
Hello,

Same here. 
@PatMyron I've tried your command, but warning still raising.

**Comment by yudao** [comment]
@PatMyron No, it's working, my apologies 👍

**Comment by amancevice** [comment]
@PatMyron I installed `cfn-lint` through Homebrew and have tried re-installing with no effect. I just tried doing it inside a Docker container as well:

```Dockerfile
FROM python
WORKDIR /var/task
RUN pip install cfn-lint
COPY template.yaml .
CMD [ "cfn-lint", "template.yaml" ]
```

```bash
docker build -t cfn-lint .
docker run --rm cfn-lint
# => There are unpublished metrics. Please make sure you call publish after you record all metrics.
```

**Comment by amancevice** [comment]
Well spotted @kddejong. Closing this issue and subscribing to the one you referenced. Cheers!
