### ISSUE TITLE
ResponseHeadersPolicyId missing from CloudFrontDistribution/Properties/DistributionConfig/CacheBehaviors

### ISSUE THREAD

**Issue by UberBen** [aws-cloudformation/cfn-lint#2175]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.56.0

*Description of issue.*
missing ResponseHeadersPolicyId in CloudFront Cache Behaviors and Default Cache Behavior.  It was recently added to CloudFront.
[cfn-lint] E3002: Invalid Property Resources/CloudFrontDistribution/Properties/DistributionConfig/CacheBehaviors/0/ResponseHeadersPolicyId
[cfn-lint] E3002: Invalid Property Resources/CloudFrontDistribution/Properties/DistributionConfig/DefaultCacheBehavior/ResponseHeadersPolicyId

Please provide as much information as possible:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-cachebehavior.html#cfn-cloudfront-distribution-cachebehavior-responseheaderspolicyid
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-defaultcachebehavior.html#cfn-cloudfront-distribution-defaultcachebehavior-responseheaderspolicyid

**Comment by kddejong** [comment]
Just released [v0.56.1](https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.56.1) which includes this property.  You can additionally run `cfn-lint --update-specs`
