### ISSUE TITLE
IPAM support for VPC: validation should only report CidrBlock as missing when IPAM properties haven't been supplied

### ISSUE THREAD

**Issue by andyhopp** [aws-cloudformation/cfn-lint#2237]
*cfn-lint version: (`cfn-lint --version`)*
0.58.2

*Description of issue.*
IPAM support for VPC: validation should only report CidrBlock as missing when IPAM properties haven't been supplied

The [attached valid template](https://github.com/aws-cloudformation/cfn-lint/files/8307251/E3003-issue.template.txt) throws `E3003 Property CidrBlock missing at Resources/VPC/Properties`

**Comment by kddejong** [comment]
This error is no longer returned however only in v1 will you get an error message if you don't include IPAM or CidrBlock
