### ISSUE TITLE
E3001 Invalid or unsupported Type AWS::Lambda::Url for resource TrainingLambdaFunctionUrl in us-east-1

### ISSUE THREAD

**Issue by nicornk** [aws-cloudformation/cfn-lint#2247]
*cfn-lint version: (`cfn-lint --version`)*

cfn-lint 0.58.4

*Description of issue.*

TrainingLambdaFunctionUrl:
  Type: AWS::Lambda::Url
  Properties:
    AuthType: "NONE"
    Cors:
      AllowOrigins:
        - '*'
    TargetFunctionArn: !GetAtt TrainingLambdaFunction.Arn

E3001 Invalid or unsupported Type AWS::Lambda::Url for resource TrainingLambdaFunctionUrl in us-east-1

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-url.html

**Comment by PatMyron** [comment]
picked up in https://github.com/aws-cloudformation/cfn-lint/pull/2245 or by running `cfn-lint -u` (which might be a bit slow)

**Comment by nicornk** [comment]
Not sure, even after running `cfn-lint -u` the issue persists.

**Comment by kddejong** [comment]
That should have picked it up.  Working on getting a release out with it included as well.
