### ISSUE TITLE
Unable to install via pip on python 3.6

### ISSUE THREAD

**Issue by subsidel** [aws-cloudformation/cfn-lint#2254]
*cfn-lint version: 0.59.0*

Fails to install on CentOS 7 via pip, with python 3.6, due to version of aws-sam-translator>=1.45.0 not being found.

Please provide as much information as possible:
Using:
`python3 x86_64 3.6.8-18.el7`
`python3-pip noarch 9.0.3-8.el7`

Running `python3.6 -m pip install cfn-lint`

Error message:
```
Collecting aws-sam-translator>=1.45.0 (from cfn-lint)
--
| Could not find a version that satisfies the requirement aws-sam-translator>=1.45.0 (from cfn-lint) (from versions: 1.5.1, 1.5.2, 1.5.3, 1.5.4, 1.6.0, 1.6.1, 1.7.0, 1.8.0, 1.9.0, 1.9.1, 1.10.0, 1.11.0, 1.12.0, 1.13.0, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.1, 1.16.0, 1.17.0, 1.18.0, 1.19.0, 1.19.1, 1.20.0, 1.20.1, 1.21.0, 1.22.0, 1.23.0, 1.24.0, 1.25.0, 1.26.0, 1.27.0, 1.28.1, 1.29.0, 1.30.0, 1.30.1, 1.31.0, 1.32.0, 1.33.0, 1.34.0, 1.35.0, 1.36.0, 1.37.0, 1.38.0, 1.39.0, 1.40.0, 1.42.0)
| No matching distribution found for aws-sam-translator>=1.45.0 (from cfn-lint)
```

`cfl-lint v0.59.0` [README][1] and [CONTRIBUTING][2] say it supports `python v3.5+` ([setup.py][0] says `python 3.6+`).

However, `aws-sam-translator` has dropped support for `python v3.6` since version `1.43.0`.   
As far as I can tell, it hasn't supported `python v3.5` at any point, the first v3+ support was in `1.20.0`, which started with `python v3.6`, but I haven't looked too hard at its support for `v3.5`.

[0]:https://github.com/aws-cloudformation/cfn-lint/blob/main/setup.py#L70
[1]:https://github.com/aws-cloudformation/cfn-lint/blob/main/README.md?plain=1#L31
[2]:https://github.com/aws-cloudformation/cfn-lint/blob/main/CONTRIBUTING.md?plain=1#L24

**Comment by PatMyron** [comment]
related: https://github.com/aws/serverless-application-model/issues/2291

**Comment by kddejong** [comment]
We no longer are supporting Python 3.6.  You can pin some older versions of SAM and cfn-lint.  You'll also still be able to run `cfn-lint --update-specs` to keep it up to date.
