### ISSUE TITLE
Invalid Property WorkGroupConfigurationUpdates - Athena::WorkGroup

### ISSUE THREAD

**Issue by nawinto99** [aws-cloudformation/cfn-lint#2262]
*cfn-lint version: 0.59.1*

*Description of issue.*

I get the error shown below when using the latest version of cfn-lint. It worked fine in previous versions of cfn-lint.
`E3002 Invalid Property Resources/MyAthenaWorkGroup/Properties/WorkGroupConfigurationUpdates`

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
```python:
  MyAthenaWorkGroup:
    Type: AWS::Athena::WorkGroup
    Properties:
      WorkGroupConfigurationUpdates:
        EnforceWorkGroupConfiguration: true
        PublishCloudWatchMetricsEnabled: true
        RequesterPaysEnabled: false
        ResultConfigurationUpdates:
          OutputLocation: "s3://abc/xyz/"
      Description: abc
      Name: abc
      State: ENABLED
```
  * If present, please add links to the (official) documentation for clarification.
  [aws-resource-athena-workgroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-athena-workgroup.html#aws-resource-athena-workgroup--examples)

**Comment by PatMyron** [comment]
This property type looks poorly modeled in the first place, looks like they decided to remodel it by removing that property:
https://github.com/ScriptAutomate/aws-cfn-resource-specs/blob/master/changelogs/v68-CHANGELOG.md#complete-removal-of-resourcetypes-andor-propertytypes

**Comment by nawinto99** [comment]
Thank you so much for providing this information. Problem solved.
