### ISSUE TITLE
E3002 Invalid Property Resources/AutoScalingGroup/Properties/DefaultInstanceWarmup

### ISSUE THREAD

**Issue by lorengordon** [aws-cloudformation/cfn-lint#2270]
*cfn-lint version: (`cfn-lint --version`)*

```
❯ cfn-lint --version
cfn-lint 0.60.0
```

*Description of issue.*

Getting an E3002 Invalid Property error on the Autoscaling Group property, `DefaultInstanceWarmup`, but this is a [valid property](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html#aws-properties-as-group-properties).

I don't see anything in the [release notes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/ReleaseHistory.html) indicating when this property was added, so I'm not really sure how to know whether a model update fixes this? Is there another resource, maybe a git repo, for checking model updates?

**Comment by PatMyron** [comment]
picked up in https://github.com/aws-cloudformation/cfn-lint/pull/2265 or by running `cfn-lint -u`

**Comment by lorengordon** [comment]
Ahh, thanks for the PR link. I was looking at commits since the last release to see if the models had been updated, and didn't see any new commits. Forgot to look at PRs 🤦 

When might that be merged, and a new release cut?

**Comment by lorengordon** [comment]
Fixed in #2265
