### ISSUE TITLE
E3001 Invalid or unsupported Type AWS::SES::EmailIdentity for resource TestSES in us-east-1

### ISSUE THREAD

**Issue by harita12** [aws-cloudformation/cfn-lint#2301]
cfn-lint version: cfn-lint 0.61.1

Getting lint validation error while creating SES identity

Resources:

    TestSES:
        Type: AWS::SES::EmailIdentity
        Properties: 
          DkimAttributes: 
              SigningEnabled: 'true'
          DkimSigningAttributes: 
            NextSigningKeyLength: RSA_2048_BIT
          EmailIdentity: !Ref DomainName
          FeedbackAttributes: 
              EmailForwardingEnabled: 'true'
          MailFromAttributes: 
              BehaviorOnMxFailure: REJECT_MESSAGE
              MailFromDomain: !Ref MailFromSubDomain

**Comment by PatMyron** [comment]
merged in https://github.com/aws-cloudformation/cfn-lint/pull/2292 for next release
(`cfn-lint -u` also picks this up until then)
