### ISSUE TITLE
E2507: Error if PolicyDocument is in S3 bucket (Fn::Transform)

### ISSUE THREAD

**Issue by leonchik1976** [aws-cloudformation/cfn-lint#2312]
*cfn-lint version: (`cfn-lint --version`)*
cfn-lint 0.61.3
*Description of issue.*
E2507: IAM Policy key Fn::Transform doesn't exist, when Fn::Transform used at PolicyDocument

Please provide as much information as possible:
* Template linting issues:
  * Please provide a CloudFormation sample that generated the issue.
IAMPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: policy-name
      PolicyDocument:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: S3 bucket object json URI

Cfn-lint uses the [CloudFormation Resource Specifications](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html) as the base to do validation. These files are included as part of the application version. Please update to the latest version of `cfn-lint` or update the spec files manually (`cfn-lint -u`)

**Comment by PatMyron** [comment]
https://github.com/aws-cloudformation/cfn-lint/issues/476
