### ISSUE TITLE
E2503 Attribute "routing.http.preserve_host_header.enabled" for ElasticLoadBalancingV2::LoadBalancer 

### ISSUE THREAD

**Issue by infoomatic** [aws-cloudformation/cfn-lint#2323]
*cfn-lint version: cfn-lint 0.61.4*

*Description of issue.*

cfn-lint gives me: 
2503 Attribute "routing.http.preserve_host_header.enabled" not allowed for load balancers with type "application"
whereas https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-loadbalancer-loadbalancerattributes.html in Properties says this is possible for application load balancers - deployment works, but the linter throws the above error.

I guess this is similar to https://github.com/aws-cloudformation/cfn-lint/issues/2100

**Comment by PatMyron** [comment]
Proposed removing this hardcoding since that rule has some of the most churn because of it:

https://github.com/aws-cloudformation/cfn-lint/pull/2184
