### ISSUE TITLE
ERROR: E3030 You must specify a valid value for Runtime (nodejs16.x)

### ISSUE THREAD

**Issue by Marline22** [aws-cloudformation/cfn-lint#2332]
*cfn-lint version: 1.9.7

cfn-lint incorrectly raises the use of nodejs.16 as an error.

Support for the value is declared in the CFN reference:

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html

The following usage in yml file will raise the error on validation:
Runtime: nodejs16.x

**Comment by PatMyron** [comment]
Unrelated to recent runtime PR: https://github.com/aws-cloudformation/cfn-lint/pull/2327

Based on your version number, you're using the old unrelated deprecated `npm` package:

https://github.com/martysweet/cfn-lint#retirement-notice

But the error in the title seems from this `pip` package
