### ISSUE TITLE
Valid policy types for AWS::AutoScaling::ScalingPolicy does not include 'PredictiveScaling'

### ISSUE THREAD

**Issue by PalringoAdmin** [aws-cloudformation/cfn-lint#2377]
### CloudFormation Lint Version

cfn-lint 0.65.1

### What operating system are you using?

macOS Monterey 12.6

### Describe the bug

When using the valid policy type of PredictiveScaling in a AWS::AutoScaling::ScalingPolicy declaration the following problem is reported:

[cfn-lint] E3030: You must specify a valid value for PolicyType (PredictiveScaling). Valid values are ["SimpleScaling", "StepScaling", "TargetTrackingScaling"]

### Expected behavior

There should be no problem reported.

### Reproduction template

  ECSPredictiveCPUScalingPolicy:
    Type: 'AWS::AutoScaling::ScalingPolicy'
    Properties:
      AutoScalingGroupName: !Ref ECSAutoScalingGroup
      PolicyType: PredictiveScaling
      PredictiveScalingConfiguration:
        MetricSpecifications:
          - TargetValue: !Ref AverageCpuPercentage
            PredefinedMetricPairSpecification:
              PredefinedMetricType: ASGCPUUtilization
        Mode: ForecastOnly  # ForecastOnly or ForecastAndScale

**Comment by kddejong** [comment]
Submitted it twice. Fixed with #2378

Should hopefully be released shortly
