### ISSUE TITLE
I3011 RDS cluster database

### ISSUE THREAD

**Issue by R00T88** [aws-cloudformation/cfn-lint#2384]
### CloudFormation Lint Version

0.65

### What operating system are you using?

Windows

### Describe the bug

[cfn-lint] I3011: The default action when replacing/removing a resource is to delete it. Set explicit values for UpdateReplacePolicy / DeletionPolicy on potentially stateful resource: Resources/*****

### Expected behavior

Cannot add UpdateReplacePolicy or DeletionPolicy for RDS database aurora

### Reproduction template

DBSAURORACLS001: # RDS Aurora Cluster
    Properties:
      BacktrackWindow: 259200
      BackupRetentionPeriod: 3
      CopyTagsToSnapshot: True
      DBClusterIdentifier: !Sub
          - 'ssc-rds-${OpCo}-${Dtap}-${Application}-${AppEnvCode}'
          - OpCo: !Ref OpCo
            Dtap: !Ref Dtap
            Application: !Ref Application
            AppEnvCode: !Ref AppEnvCode
      DBClusterParameterGroupName: !Ref 'DBSAURORACPG001'
      DBSubnetGroupName: !Ref 'DBSAURORASBT001'
      EnableCloudwatchLogsExports:
        - audit
        - general
        - slowquery
        - error
      Engine: !FindInMap [RdsEngineTypeMap, !Ref "AWS::Region", DBSAURORACLS001]
      EngineMode: provisioned
      EngineVersion: !FindInMap [RdsEngineVersionTypeMap, !Ref "AWS::Region", DBSAURORACLS001]
      MasterUserPassword: !If
        - UseDbSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'MasterUserPassword'
      MasterUsername: !If
        - UseDbSnapshot
        - !Ref 'AWS::NoValue'
        - !Ref 'MasterUserName'
      SnapshotIdentifier: !If
        - UseDbSnapshot
        - !Ref 'SnapshotIdentifier'
        - !Ref 'AWS::NoValue'
      PreferredBackupWindow: "00:00-01:00"
      PreferredMaintenanceWindow: "sun:02:00-sun:04:00"
      StorageEncrypted: True
      Tags:
        - Key: Name
          Value: !Sub
            - 'ssc-rds-${OpCo}-${Dtap}-${Application}-${AppEnvCode}'
            - OpCo: !Ref OpCo
              Dtap: !Ref Dtap
              Application: !Ref Application
              AppEnvCode: !Ref AppEnvCode
        - Key: OpCo
          Value: !Ref OpCo
        - Key: Dtap
          Value: !Ref 'Dtap'
        - Key: Owner
          Value: !Ref 'Owner'
        - Key: Creator
          Value: !Ref 'Creator'
        - Key: Application
          Value: !Ref 'Application'
        - Key: Description
          Value: Digital Assessment MySql Aurora RDS
        - Key: Ec2ctl
          Value: n/a
        - Key: EnvCode
          Value: !Ref 'EnvCode'
        - Key: AppCodeExclude
          Value: True
      VpcSecurityGroupIds:
        - !Ref 'DBSAURORASG001'
    Type: AWS::RDS::DBCluster

**Comment by kddejong** [comment]
Can you provide links to documentation on this?

**Comment by R00T88** [comment]
@kddejong 

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html

![image](https://user-images.githubusercontent.com/9050487/192872508-2f442152-ea05-426c-bf5a-a3de64728544.png)

**Comment by PatMyron** [comment]
While the default is different for some RDS resource types, I believe all defaults can still be overridden with explicit policies as that rule is encouraging. So _`"The default action [...]"`_ may not be accurate for RDS, but _`"Set explicit values"`_ is still best practice regardless. (Differing defaults was actually one reason the rule was written since inconsistent defaults are confusing and a false sense of safety)

**Comment by R00T88** [comment]
@PatMyron if i specify "DeletionPolicy" attribute on resource AWS::RDS::DBCluster i receive another error

![image](https://user-images.githubusercontent.com/9050487/192876143-fbd200af-ffa2-443b-9f0e-7ac757a30ed7.png)

**Comment by PatMyron** [comment]
Those policies are general [attributes](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-product-attribute-reference.html) rather than type-specific properties, so they're set an indentation level above properties:
```yaml
Resources:
  RDSDBCluster:
    Type: AWS::RDS::DBCluster
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      Engine: aurora
      MasterUsername: MasterUsername
      MasterUserPassword: MasterUserPassword
```

**Comment by R00T88** [comment]
@PatMyron Thanks!
