### ISSUE TITLE
Support CloudFront HTTP/3 Property

### ISSUE THREAD

**Issue by lucasvieirasilva** [aws-cloudformation/cfn-lint#2423]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

A few months ago AWS announces the HTTP/3 support for CloudFront https://aws.amazon.com/about-aws/whats-new/2022/08/amazon-cloudfront-supports-http-3-quic/ which is also supported by the CloudFormation resource https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-distributionconfig.html#cfn-cloudfront-distribution-distributionconfig-httpversion

There are 2 new values (`http2and3` and `http3`) that are not supported in the cfn-lint,

Could you please add them?

### Describe the solution you'd like

Add `http2and3` and `http3` to `HttpVersion` property in the `AWS::CloudFront::Distribution` CloudFormation resource.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by PatMyron** [comment]
picked up a couple months ago in https://github.com/aws-cloudformation/cfn-lint/pull/2324, upgrade to latest `cfn-lint` for support

**Comment by lucasvieirasilva** [comment]
> picked up a couple months ago in #2324, upgrade to latest `cfn-lint` for support

You're right, thank you!
