### ISSUE TITLE
Inline lambda mistakenly failing as over 4096 characters

### ISSUE THREAD

**Issue by kenlawrie1** [aws-cloudformation/cfn-lint#2446]
### CloudFormation Lint Version

0.69.0

### What operating system are you using?

linux

### Describe the bug

Our pipelines started failing this morning, as cnf-lint detects inline Lambda's as over 4096 characters
However as they are uploaded to S3 before deployment, they do not have this 4096 restriction, could this be a warning rather than a failure?

### Expected behavior

Should be a warning, as the error is not always applicable

### Reproduction template

Cant supply template :-)

**Comment by PatMyron** [comment]
Just fixed and released:
https://github.com/aws-cloudformation/cfn-lint/pull/2444
