### ISSUE TITLE
Load specs only when needed

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#2468]
### Describe the feature you'd like to request

Currently we load all region specs every cfn-lint execution even if the user is using one region.  

### Describe the solution you'd like

With this change we would only load the specs when they are requested.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by PatMyron** [comment]
How long do they take to load? Could regions just be loaded in parallel?

**Comment by kddejong** [comment]
They could be loaded parallel, that may help as well.  Right now all the regions are loaded even for operations that don't require the specs `cfn-lint --version` while the speed isn't horrible its unnecessary cycles.

**Comment by kddejong** [comment]
Going to close this issue.  It will come with v1
