### ISSUE TITLE
new region added incorrectly.

### ISSUE THREAD

**Issue by whoDoneItAgain** [aws-cloudformation/cfn-lint#2484]
### CloudFormation Lint Version

0.71.1

### What operating system are you using?

n/a

### Describe the bug

#2478 

not sure the downstream implications but eu-central-1's name was updated to Zurich and eu-central-2 was added as Frankfurt.

### Expected behavior

eu-central-1 is frankfort
eu-central-2 is zurich

### Reproduction template

n/a

**Comment by kddejong** [comment]
Double check my work here: #2480 

Turns out that needed another fix too.

**Comment by kddejong** [comment]
Resolved.
