### ISSUE TITLE
AWS::EFS::FileSystem -> ThroughputMode E3030: You must specify a valid value for ThroughputMode

### ISSUE THREAD

**Issue by magiktm** [aws-cloudformation/cfn-lint#2506]
### CloudFormation Lint Version

0.72.1

### What operating system are you using?

Windows

### Describe the bug

There's an error detected in the AWS::EFS::FileSystem resource type when using ThroughputMode: elastic
E3030: You must specify a valid value for ThroughputMode (elastic). Valid values are ["bursting", "provisioned"]

According to https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-efs-filesystem.html#cfn-efs-filesystem-throughputmode the supported types are bursting | elastic | provisioned and this configuration should not cause an error.  

### Expected behavior

No error then using ThroughputMode: elastic into an AWS::EFS::FileSystem resource type

### Reproduction template

AWSTemplateFormatVersion: 2010-09-09  
EFS:
    Type: 'AWS::EFS::FileSystem'
    Properties:
      BackupPolicy:
        Status: ENABLED
      Encrypted: true
      LifecyclePolicies:
        - TransitionToIA: AFTER_30_DAYS
      FileSystemTags:
        - Key: Name
          Value: efs-file-system
        - Key: ApplicationRole
          Value: role-efs-file-system
      KmsKeyId: 'alias/aws/elasticfilesystem'
      ThroughputMode: elastic

**Comment by kddejong** [comment]
Automated maintenance picked it up:
https://github.com/aws-cloudformation/cfn-lint/pull/2493/files#diff-a5a6f378b19287fd419ef6c9edf44d4493163add0a727420af026573a02f165a
