### ISSUE TITLE
[cfn-lint] E3001: Invalid or unsupported Type AWS::ControlTower::EnabledControl for resource XXXXXXXX in us-east-1

### ISSUE THREAD

**Issue by Jguzmanr07** [aws-cloudformation/cfn-lint#2533]
### CloudFormation Lint Version

cfn-lint 0.60.1

### What operating system are you using?

Mac

### Describe the bug

cfn-lint version: cfn-lint 0.60.1

Description of issue.
[cfn-lint] E3001: Invalid or unsupported Type AWS::ControlTower::EnabledControl for resource GuardrailsProd in us-east-1.

Please provide as much information as possible:
    

If present, please add links to the (official) documentation for clarification.
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-controltower-enabledcontrol.html Validate if the issue still exists with the latest version of cfn-lint and/or the latest Spec files
Confirmed that issue persists after updating cfn-lint to 0.60.1 and running cfn-lint --update-specs. Confirmed template deploys successfully without linting.

### Expected behavior

Don´t report errro on validation of template

### Reproduction template

AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  "Configure AWS Guardrails Account AWS Master."

Resources:

#### Recursos para la OU PRODUCTION #####

  # Disallow Creation of Access Keys for the Root User
  rAWSGRRUAKProd:
    Type: AWS::ControlTower::EnabledControl
    Properties:
      ControlIdentifier: 'arn:aws:controltower:us-east-2::control/EXAMPLE_NAME'
      TargetIdentifier: 'arn:aws:organizations::01234567890:ou/o-EXAMPLE/ou-zzxx-zzx0zzz2'

**Comment by kddejong** [comment]
Update cfn-lint package to the most recent version https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.72.5 or run `cfn-lint --update-specs`
