### ISSUE TITLE
E3002 Invalid Resource Type - AWS::SSO::PermissionSet PermissionsBoundary

### ISSUE THREAD

**Issue by WarrEagle** [aws-cloudformation/cfn-lint#2538]
### CloudFormation Lint Version

0.59.1

### What operating system are you using?

Windows 10

### Describe the bug

Errors during linting and as part of our pipeline build. Complaints (E3002) that PermissionsBoundary is an invalid resource property. AWS Documentation indicates otherwise. CFN template works fine in CF.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-sso-permissionset.html

### Expected behavior

Correct linting

### Reproduction template

PermissionSetWithCustomerManagedPolicyReferenceForPermissionsBoundary:
  Type: AWS::SSO::PermissionSet
   Properties:
     InstanceArn: 'arn:aws:sso:::instance/ssoins-instanceId'
     Name: 'PermissionSetWithCmpPb'
     Description: 'This is a sample permission set.'
     SessionDuration: 'PT8H'
     ManagedPolicies:
     - 'arn:aws:iam::aws:policy/AdministratorAccess'
     CustomerManagedPolicyReferences:
     - Name: 'MyCustomPolicyName'
       Path: '/myCustomPath/'
     - Name: 'AnotherCustomPolicyName'
     - Name: 'YetAnotherCustomPolicyName'
       Path: '/'
     PermissionsBoundary:
       CustomerManagedPolicyReference:
         Name: PolicyName
         Path: /myPolicyPath/

**Comment by kddejong** [comment]
v0.59.1 is pretty far behind.  Can you update to our newest release https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.72.5 or run `cfn-lint --update-specs`.

The specs we use are updated weekly (usually) so we are releasing new versions which include the results of running `cfn-lint --update-specs`.

I don't know what release included `AWS::SSO::PermissionSet` but I know for sure its in v0.72.5.
