### ISSUE TITLE
E0002/W1001 Edge Case: Fn::Transform in Fn::Sub.String

### ISSUE THREAD

**Issue by LaikaN57** [aws-cloudformation/cfn-lint#2587]
### CloudFormation Lint Version

0.73.1

### What operating system are you using?

macOS 13.1 (22C65)

### Context
`W1001` Checks for `Ref`'s to conditional resources in `Fn::Sub`'s `String` parameter (ie. 0th list index). 

### 🐛 Bug
Using an `Fn::Transform` breaks this check during a regex scan for `Ref` tokens in the `Fn::Sub`'s `String` parameter as the regex is expecting a string type.

### 🔍 Stack Trace
```
E0002 Unknown exception while processing rule W1001: Traceback (most recent call last):
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/rules/__init__.py", line 320, in run_check
    return check(*args)
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/rules/__init__.py", line 44, in wrapper
    results = match_function(self, filename, cfn, *args, **kwargs)
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/rules/__init__.py", line 202, in matchall
    return self.match(cfn)  # pylint: disable=E1102
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/rules/functions/RelationshipConditions.py", line 99, in match
    string_params = cfn.get_sub_parameters(sub_string[0])
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/template.py", line 627, in get_sub_parameters
    string_params = regex.findall(sub_string)
TypeError: expected string or bytes-like object
```

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/206373/218685443-c0c7431f-a1b9-4403-8236-a9a927486bdb.png">

### Expected behavior

I would expect that `Fn::Sub`'s which contain an `Fn::Transform` as the `String` parameter to be evaluated "post-transform" for `W1001`.

Alternatively, I would expect that using an `Fn::Transform` as the `String` parameter in an `Fn::Sub` would result in a different warning as some type of "bad practice".

### 📖 Doc Findings

> For the String parameter, you can't use any functions. You must specify a string value.

[AWS CloudFormation User Guide - `Fn::Sub` Supported functions](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-sub.html#:~:text=For%20the%20String%20parameter%2C%20you%20can%27t%20use%20any%20functions.%20You%20must%20specify%20a%20string%20value.)

I believe the doc is making this statement as it applies to "post-transform". I will open a related docfix issue against that page to make this entry more correct.

### Reproduction template

**Partial**

```yaml
Resources:
  Resource1:
    Type: Custom::ResourceType1
    Properties:
      ServiceToken:
        Fn::ImportValue:
          Fn::Sub: ${Stage1Stack}-ServiceToken1
      Data:
        Fn::Sub:
          - Fn::Transform:
              Name: Jinja
              Parameters:
                OutputFormat: String
                JinjaTemplate:
                  # [REDACTED - This template has been heavily redacted but
                  # one could image complex Jinja template logic.]
                  Fn::Base64: |
                    - rolearn: "${InstanceRole}"
                      username: {% raw %}'system:node:{{EC2PrivateDNSName}}'{%- endraw %}
                    - rolearn: arn:aws:iam::${AWS::AccountId}:role/AWSServiceRoleForAmazonEMRContainers
                      username: emr-containers
          - InstanceRole:
              Fn::ImportValue:
                Fn::Sub: '${Stage1Stack}-InstanceRole'
```

**Comment by LaikaN57** [comment]
Looks like we might have regressed? https://github.com/aws-cloudformation/cfn-lint/pull/920

**Comment by LaikaN57** [comment]
This seems to be a non-fatal issue here as well:

https://github.com/aws-cloudformation/cfn-lint/blob/f4df1d27ec8b25bd5b081edacfba0bd6e4d6eebf/src/cfnlint/graph.py#L218-L225

### 🔍 Stack Trace

```
2023-02-14 01:36:53,275 - cfnlint.template - ERROR - Encountered unknown error while building graph: expected string or bytes-like object
Traceback (most recent call last):
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/template.py", line 48, in __init__
    self.graph = Graph(self)
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/graph.py", line 92, in __init__
    self._add_subs(cfn)
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/graph.py", line 223, in _add_subs
    sub_parameters = self._find_parameter(value[0])
  File "/Users/akennedy/src/catapult/.venv/lib/python3.10/site-packages/cfnlint/graph.py", line 268, in _find_parameter
    return regex.findall(string)
TypeError: expected string or bytes-like object
```

**Comment by PatMyron** [comment]
> Looks like we might have regressed? #920

---

That PR is a separate rule, but likely regressed in https://github.com/aws-cloudformation/cfn-lint/pull/2525

---

More generally, tracking transform support in https://github.com/aws-cloudformation/cfn-lint/issues/476. It's been open for a while, but I still think some general solution will be more sustainable than if-statements across all individual rules that could be affected by transforms

**Comment by kddejong** [comment]
I'm seeing errors across the board.  I think what makes sense is to validate that the `get_sub_parameters` regex match validate that the `sub_string` is actually a string before running regex on it.  It should be on the rule to validate the structure of the Fn::Sub to know if this properly configured.

```
E0002 Unknown exception while processing rule W2001: expected string or bytes-like object
local/issue/2587.yaml:1:1

E0002 Unknown exception while processing rule W1001: expected string or bytes-like object
local/issue/2587.yaml:1:1

E0002 Unknown exception while processing rule E1019: expected string or bytes-like object
local/issue/2587.yaml:1:1
```
with that change:
```
E1019 Parameter Stage1Stack for Fn::Sub not found at Resources/Resource1/Properties/ServiceToken/Fn::ImportValue/Fn::Sub
local/issue/2587.yaml:7:11

E1019 Subs first element should be of type string for Resources/Resource1/Properties/Data/Fn::Sub
local/issue/2587.yaml:10:13

E1019 Parameter Stage1Stack for Fn::Sub not found at Resources/Resource1/Properties/Data/Fn::Sub/1/InstanceRole/Fn::ImportValue/Fn::Sub
local/issue/2587.yaml:24:17
```

**Comment by LaikaN57** [comment]
@kddejong Any insights on the documentation discrepancy? (Not sure where/what the source of truth here is.)

**Comment by kddejong** [comment]
@LaikaN57 I'll look into it

**Comment by kddejong** [comment]
So talked to @TheDanBlanco and transforms are run before anything else is processed.  So Transform can be any place in a template including in a sub.  I think the documentation around what is supported in a Sub is meant to represent what is supported once all the Transforms are complete.

**Comment by LaikaN57** [comment]
ok I think my doc fix request still stands in that case.

Thanks for the quick turn-around on this!

ref: https://github.com/awsdocs/aws-cloudformation-user-guide/pull/1306

**Comment by kddejong** [comment]
We will have this fix in the next release.
