### ISSUE TITLE
E2532 does not support ItemProcessor for State of Type Map

### ISSUE THREAD

**Issue by jnplthr** [aws-cloudformation/cfn-lint#2592]
```
$ cfn-lint --version
cfn-lint 0.73.1
```

Description of issue:
I get following error when trying to use `ItemProcessor` in a `Map` state:

```E2532 State Machine Definition key (ItemProcessor) for State (x) of Type (Map) is not valid```

It's a valid construct:
https://docs.aws.amazon.com/step-functions/latest/dg/concepts-asl-use-map-state-inline.html#itemprocessor

```
            "stateName": {
              "MaxConcurrency": 10,
              "Type": "Map",
              "End": true,
              "ItemsPath": "$",
              "ResultPath": "$",
              "ItemProcessor": {}
            },
```

**Comment by kddejong** [comment]
Will be released shortly.  Was fixed in this PR https://github.com/aws-cloudformation/cfn-lint/pull/2577
