### ISSUE TITLE
E3502 taking 20min+ to process

### ISSUE THREAD

**Issue by fpmrqs** [aws-cloudformation/cfn-lint#2595]
**cfn-lint 0.73.1**

Hello, 

We have a cfn template containing a very configurable AWS::IAM::ManagedPolicy resource. The way we can configure this is via a set of six parameters that allow us to choose which services we need permissions for.

cfn-lint is taking a very long time (up to 30 minutes) to analyse this. When running in debug mode, we can see this is due to rule E3502. 

- Is this because cfn-lint is trying every single combination of parameters to resolve this resource?
- We are thinking of skipping this rule for now, unless anyone can suggest a better solution?

Thank you!

**Comment by PatMyron** [comment]
https://xkcd.com/303/

**Comment by kddejong** [comment]
#2624 may help with this as well
