### ISSUE TITLE
Cfn-Lint issuing E1010 error on the new grafana cft updates for the GetAtt outputs

### ISSUE THREAD

**Issue by deltaaj2016** [aws-cloudformation/cfn-lint#2605]
### CloudFormation Lint Version

0.61.0

### What operating system are you using?

Windows

### Describe the bug

Using the new updates for cloudformation template for the AWS managed grafana instance. When running through CFN lint I was receiving a E3001 and was able to implement the metadata and ignore that error. However, I am also getting the E1010 stating that the outputs for grafana that I am using arent available. My team and I have validated the syntax and have tried using the long and short for of GetAtt to try and obtain the outputs from the grafana workspace creation, but we are still getting the E1010 error. We tried to add that to the metadata ignoring the E3001 and cfn lint is still erroring on E1010 and not ignoring that error. We tried removing E3001 and still go the same error, so at this point we feel it could be a bug within cfn lint with the new cft that has been published for AWS managed grafana.
![CFN Lint Errors](https://user-images.githubusercontent.com/126714294/222244794-d6c8b72f-2ced-4148-823e-08e60f05f403.JPG)

### Expected behavior

![CFT Code](https://user-images.githubusercontent.com/126714294/222244808-f0ba7dcd-53c4-48f2-b347-afd24ce2a2e3.JPG)
The expected behavior would be to either not get the E1010 error according to the AWS documentation or get the E1010 to work when you set up metadata to ignore E1010.

### Reproduction template

`AWSTemplateFormatVersion: "2010-09-09"
Description: CFT template deploys a Grafana Workspace
  
Resources:
  GrafanaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: 'delegate-admin-role'
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - grafana.amazonaws.com
            Action:
              - 'sts:AssumeRole'
            Condition:
              StringEquals:
                "aws:SourceAccount": !Sub "${AWS::AccountId}"
              StringLike:
                "aws:SourceArn": !Sub "arn:aws:grafana:us-east-1:${AWS::AccountId}:/workspaces/*"
      Path: "/"
      ManagedPolicyArns:
        - !Sub arn:aws:iam::${AWS::AccountId}:policy/cft-developer-iam-access-policy
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSXRayDaemonWriteAccess
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSGrafanaAccountAdministrator
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSSOMasterAccountAdministrator
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSSODirectoryAdministrator
        - !Sub arn:${AWS::Partition}:iam::aws:policy/AWSSSOMemberAccountAdministrator
      PermissionsBoundary: !Sub arn:aws:iam::${AWS::AccountId}:policy/cft-developer-boundary-policy
      ## Please add policy here as required
      Policies:
      - PolicyName: VPCConfigPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - "ec2:CreateNetworkInterface"
              - "ec2:DeleteNetworkInterface"
              - 'ec2:CreateSecurityGroup'
              - 'ec2:RevokeSecurityGroupEgress'
              - 'ec2:AuthorizeSecurityGroupEgress'
              - 'ec2:Describe*'
            Resource: "*"
      - PolicyName: ReadLogsAndMetricsPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - logs:GetLogGroupFields
              - logs:StartQuery
              - logs:StopQuery
              - logs:GetQueryResults
              - cloudwatch:DescribeAlarmsForMetric
              - cloudwatch:DescribeAlarmHistory
              - cloudwatch:DescribeAlarms
              - cloudwatch:ListMetrics
              - cloudwatch:GetMetricData
              - cloudwatch:GetInsightRuleReport
              - cloudwatch:PutMetricData
            Resource: "*"
      - PolicyName: AWSSingleSignOnPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - sso:DescribeRegisteredRegions
            Resource: "*"
      - PolicyName: GrafanaPolicy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'grafana:*'
              - 'kms:*'
              - 'ec2:*'
              - 'ssm:GetParameter'
              - 'ssm:PutParameter'
              - 'config:PutEvaluations'
              - 'secretsmanager:GetSecretValue'
              - 'tag:GetResources'
            Resource: 
              - '*'
      - PolicyName: S3Policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 's3:*'
            Resource: 
              - '*'
      - PolicyName: AmazonGrafanaAthenaAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'athena:*'
            Resource: 
              - '*'
      - PolicyName: AmazonGrafanaGlueAccess
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - 'glue:*'
            Resource: 
              - '*'
  GrafanaWorkspace:
    Type: AWS::Grafana::Workspace
    Properties:
      Name: "GrafanaWS"
      Description: "Grafana Workspace Dashboard"
      AccountAccessType: "CURRENT_ACCOUNT"
      AuthenticationProviders:
        - SAML
      DataSources:
        - ATHENA
      PermissionType: "CUSTOMER_MANAGED"
      RoleArn: !Ref GrafanaExecutionRole
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E1010
            - E3001  
Outputs:
  WorkspaceEndpoint:
    Value: !GetAtt GrafanaWorkspace.Endpoint
  WorkspaceStatus:
    Value: !GetAtt GrafanaWorkspace.Status
  GrafanaVersion:
    Value: !GetAtt GrafanaWorkspace.GrafanaVersion
  WorkspaceId:
    Value: !Ref GrafanaWorkspace`

**Comment by PatMyron** [comment]
> 0.61.0

[`0.61.0` was released last May](https://github.com/aws-cloudformation/cfn-lint/releases/tag/v0.61.0), upgrade `cfn-lint` for new CloudFormation type support

**Comment by kddejong** [comment]
if you installed using pip you would run `pip install --upgrade cfn-lint` this would upgrade cfn-lint to v0.74.0
