### ISSUE TITLE
Support reading Env Vars for default region

### ISSUE THREAD

**Issue by jfuss** [aws-cloudformation/cfn-lint#2617]
### Is this feature request related to a new rule or cfn-lint capabilities?

New capability

### Describe the feature you'd like to request

I would like CFN Lint to read Env Vars for setting a default region. This was something SAM CLI ran into with it's integrations with CFN Lint: SAM CLI's issue: https://github.com/aws/aws-sam-cli/issues/4844

### Describe the solution you'd like

Following https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-envvars.html seems like the best thing to do. That is `AWS_DEFAULT_REGION` will be set but can be overrode by `AWS_REGION`. If both are not in the shell and no region is passed in, we set the region to `us-east-1` as it does today.

### Additional context

This may change behavior for some customers if they have one of those env vars set but rely on the current default. I think reading the env vars, leads to an overall better experience but something to consider none the less.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Release in v0.75.0
