### ISSUE TITLE
Please Add Support for dotnet6 Runtime

### ISSUE THREAD

**Issue by DrewArdner** [aws-cloudformation/cfn-lint#2654]
### Describe the feature you'd like to request

Lambda configuration setup to use `dotnet6` runtime, and linter is throwing error that it is not a valid runtime.

### Describe the solution you'd like

Please include this as a valid runtime option for lambda configuration, as it's an option one has when deploying lambdas in AWS.

### Additional context

[cfn-lint] E3030: You must specify a valid value for Runtime (dotnet6). Valid values are ["dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7"]

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Looking into this.  It should be there by now.

**Comment by kddejong** [comment]
You need to update cfn-lint.  If you installed via pip you can run `pip install --upgrade cfn-lint`.  Depending on what version you are running you may be able to also run `cfn-lint --upgrade-specs`
