### ISSUE TITLE
Custom rules not working

### ISSUE THREAD

**Issue by mateuspok** [aws-cloudformation/cfn-lint#2761]
### CloudFormation Lint Version

cfn-lint 0.77.6

### What operating system are you using?

Alpine Container

### Describe the bug

Trying a custom rules for API GW checks and didn't work, so I tried with the examples from Readme.md for EC2 and didn't work at all.

custom_rules.txt
AWS::EC2::Instance InstanceSize NOT_EQUALS "m4.16xlarge" WARN "This is an expensive instance type, don't use it"

cfn-lint template.yml -z custom_rules.txt

Doesn't return nothing.

### Expected behavior

W9001  This is an expensive instance type, don't use it
mqtemplate.yml:6:17

### Reproduction template

AWSTemplateFormatVersion: "2010-09-09"
Resources:
        myInstance:
                Type: AWS::EC2::Instance
                Properties:
                        InstanceType: m4.16xlarge
                        ImageId: ami-asdfef

**Comment by shahamy** [comment]
In the example template, there is no `InstanceSize` so no warn will output. It might be a typo where you meant `InstanceType` instead
