### ISSUE TITLE
physical resource name limit

### ISSUE THREAD

**Issue by blade2005** [aws-cloudformation/cfn-lint#2797]
### Describe the feature you'd like to request

I want to be able to determine before launching CFN if any resources have names which exceeds the service limitations.

Lambda functions limit is 64 characters
buckets are limited to 64 characters
glue jobs are 255 characters
event bridge rules are 64 characters.

If I've use CDK to dynamically generate the names (so they are static in the outputted cfn) the names may exceed the limitations of the individual service

### Describe the solution you'd like

an error generated if any resources with static names(no sub or ref support) has a name which exceeds the max length supported by those resources.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by ashemedai** [comment]
@kddejong Did a quick check of the code base, but isn't this already (largely) implemented via src/cfnlint/rules/resources/properties/StringSize.py that fetches `StringMin` and `StringMax` (E3033)?

If I create a template of an `AWS::S3::Bucket` with a `BucketName` longer than 63 characters I get this:
```sh
$ cfn-lint s3-bucket.yml
E3033 String has to have length between 3 and 63 at Resources/S3Bucket/Properties/BucketName. Current length 71.
```

**Comment by kddejong** [comment]
@ashemedai I think you're right

- [X] Lambda functions limit is 64 characters
- [X] buckets are limited to 64 characters
- [ ] glue jobs are 255 characters
- [ ] event bridge rules are 64 characters.

Shouldn't be hard to add the other two as we have the process to do this.

**Comment by kddejong** [comment]
This PR should take care of the other two

**Comment by ashemedai** [comment]
@kddejong Fastest would be to get a proper entry to src/cfnlint/data/CloudSpecs/us-east-1.json e.g.

```json
  "AWS::Glue::Job.Name": {
  "AllowedPatternRegex": "^[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*$",
  "StringMax": 255,
  "StringMin": 1
  },
  "AWS::Events::Rule.Name": {
  "AllowedPatternRegex": "^[\.\-_A-Za-z0-9]+$",
  "StringMax": 64,
  "StringMin": 1
  },
```

It currently does not have such an entry for Glue Job Name or Events Rules Name that I can spot quickly. The pattern matches might need some tweaking between what I found in documentation and proper JSON/JavaScript regex.

**Comment by kddejong** [comment]
@ashemedai we can for sure build out some more additions here. As these resources move to the registry we should see these values auto-populate as well.
