### ISSUE TITLE
Add Support For 'RetainExceptOnCreate' Deletion Policy

### ISSUE THREAD

**Issue by SyphonxZA** [aws-cloudformation/cfn-lint#2835]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

When setting a resources DeletionPolicy to 'RetainExceptOnCreate', the following error occurs:

[cfn-lint] E3035: DeletionPolicy should be only one of Delete, Retain, Snapshot at Resources/KmsKey/DeletionPolicy

### Describe the solution you'd like

RetainExceptOnCreate should be added as an acceptable value.

### Additional context

https://aws.amazon.com/about-aws/whats-new/2023/07/aws-cloudformation-deletion-policies-dev-test-cycle/

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Released.
