### ISSUE TITLE
Neptune::DBCluster missing properties

### ISSUE THREAD

**Issue by kenslej** [aws-cloudformation/cfn-lint#2858]
### CloudFormation Lint Version

0.79.7 

### What operating system are you using?

Linux

### Describe the bug

I am getting E3002 Invalid Property Resources/rNeptuneDBCluster/Properties/DBPort

The DBPort property is found in the definition for AWS::Neptune::DBCluster :
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-neptune-dbcluster.html

There is no AWS::Neptune::DBCluster.DBPort in /src/cfnlint/data/CloudSpecs/us-east-1.json even though it is listed as a property of AWS::Neptune::DBCluster

### Expected behavior

Acceptance of DBPort Property

### Reproduction template

pDBClusterPort:
  Type: Number
  Default: 4567
  Description: Enter the port of your Neptune cluster

rNeptuneDBCluster:
  Type: 'AWS::Neptune::DBCluster'
  DeletionPolicy: Snapshot
  UpdateReplacePolicy: Snapshot
  Properties:
    EngineVersion: '1.2'
    DBClusterIdentifier:
      "Fn::Join":
        - "-"
        - Ref: pApplicationNameLC
        - Ref: pDBClusterName
    DBPort: !Ref pDBClusterPort

**Comment by kddejong** [comment]
You sure you are on cfn-lint 0.79.7.  I'm seeing the DBPort property in https://raw.githubusercontent.com/aws-cloudformation/cfn-lint/v0.79.7/src/cfnlint/data/CloudSpecs/us-east-1.json

**Comment by kddejong** [comment]
Willing to re-open as needed but I believe this value should be in the recent releases.
