### ISSUE TITLE
Due to new NLB functions, Security Groups can now be applied to NLBs.  cfn-lint marks this as an error.

### ISSUE THREAD

**Issue by johnowens00** [aws-cloudformation/cfn-lint#2860]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

Due to a recent change in AWS NLB functionality, you can now associate a Security Group with an NLB.  cfn-lint marks SecurityGroup data in a network type load balancer stanza as an error.  

### Describe the solution you'd like

Update the rules for NLB load balancer stanzas to not flag the use of a SecurityGroup descriptor node as invalid. 

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Fixed in #2853 and released with v0.79.8.
