### ISSUE TITLE
Python3.12 support and nodejs20.x

### ISSUE THREAD

**Issue by leandrodamascena** [aws-cloudformation/cfn-lint#2948]
### Describe the feature you'd like to request

Could you please add python 3.12 and nodejs20.x?

`E3030 You must specify a valid value for Runtime (python3.12). Valid values are ["dotnet6", "dotnetcore1.0", "dotnetcore2.0", "dotnetcore2.1", "dotnetcore3.1", "go1.x", "java11", "java17", "java8", "java8.al2", "nodejs", "nodejs10.x", "nodejs12.x", "nodejs14.x", "nodejs16.x", "nodejs18.x", "nodejs4.3", "nodejs4.3-edge", "nodejs6.10", "nodejs8.10", "provided", "provided.al2", "python2.7", "python3.10", "python3.11", "python3.6", "python3.7", "python3.8", "python3.9", "ruby2.5", "ruby2.7", "ruby3.2"]`

CDK already added - https://github.com/aws/aws-cdk/releases/tag/v2.108.0 and https://github.com/aws/aws-cdk/releases/tag/v2.107.0

boto3 already added - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lambda/client/create_function.html 
![image](https://github.com/aws-cloudformation/cfn-lint/assets/4295173/787231df-7483-4279-8445-787a2056719d)

botocore - https://github.com/boto/botocore/blob/develop/botocore/data/lambda/2015-03-31/service-2.json#L5237

### Describe the solution you'd like

Add support.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Included in pr #2947

**Comment by kddejong** [comment]
Nodejs20.x was already there.  Python3.12 is now included in v0.83.3
