### ISSUE TITLE
License of jsonschema fork in v1 branch?

### ISSUE THREAD

**Issue by musicinmybrain** [aws-cloudformation/cfn-lint#2949]
### CloudFormation Lint Version

cfn-lint 1.2.0.a1

### What operating system are you using?

Fedora Linux

### Describe the bug

Given that most of the code in [`src/cfnlint/jsonschema` in the `v1` branch](https://github.com/aws-cloudformation/cfn-lint/tree/v1.2.1.a1/src/cfnlint/jsonschema) is derived from https://github.com/python-jsonschema/jsonschema, which is available under a standard [MIT license](https://github.com/python-jsonschema/jsonschema/blob/v4.19.2/COPYING), can these files really be said to be available under the overall `MIT-0` license? The `MIT` license has attribution requirements (“The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.”) that don’t seem to be respected here.

https://github.com/aws-cloudformation/cfn-lint/blob/bf0e098922469418a9712bc7ea2b49745f6a62f0/src/cfnlint/jsonschema/_filter.py#L3

https://github.com/aws-cloudformation/cfn-lint/blob/bf0e098922469418a9712bc7ea2b49745f6a62f0/src/cfnlint/jsonschema/_filter.py#L7-L8

### Expected behavior

The attribution requirements of the original `jsonschema` license are respected, or if its authors agreed to make it available under `MIT-0` for use in `cfn-lint`, this is clearly indicated.

### Reproduction template

N/A

**Comment by kddejong** [comment]
Thanks for reporting this.  Worked with some of my internal team members to validate our approach and verbiage when changing the license types for this code.  I think we have it better now but please let me know if you have any more concerns and thanks for submitting this issue.

**Comment by musicinmybrain** [comment]
It looks like these files now preserve the original copyright and license statement, e.g.

https://github.com/aws-cloudformation/cfn-lint/blob/943e723cb2995dd6598ed1bb1c18b9a4633bf144/src/cfnlint/jsonschema/_utils.py#L2-L12

and have

https://github.com/aws-cloudformation/cfn-lint/blob/943e723cb2995dd6598ed1bb1c18b9a4633bf144/src/cfnlint/jsonschema/_utils.py#L14

which seems adequate to me as a Fedora packager. It would be nicer if the jsonschema license were available in a separate license file and not only in the source-code comments, but I think the current state of the `main` branch should be acceptable as-is.

Thank you for investigating this and for following up.
