### ISSUE TITLE
Support Sagemaker StoppingCondition

### ISSUE THREAD

**Issue by nartz** [aws-cloudformation/cfn-lint#3043]
### Describe the feature you'd like to request

Support Sagemaker 'StoppingCondition' - currently recognized as invalid property

### Describe the solution you'd like

Support Sagemaker 'StoppingCondition' - currently recognized as invalid property

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
`StoppingCondition` is supported across many different Sagemaker resource types.  Which resource type are you using? Have you updated cfn-lint to the most recent version?

**Comment by nartz** [comment]
Resource type: AWS::SageMaker::Pipeline
E3002 Invalid Property Resources/SageMakerPipeline/Properties/StoppingCondition

I ran with --update-specs and received the same error

**Comment by nartz** [comment]
Actually it appears this might just be invalid - going to close this one.
