### ISSUE TITLE
The load balancer name cannot be longer than 32 characters in AWS::ElasticLoadBalancingV2::LoadBalancer

### ISSUE THREAD

**Issue by johnanand707** [aws-cloudformation/cfn-lint#3259]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

Failure Details:
" Application LoadBalancer CREATE_FAILED: Resource handler returned message: "The load balancer name 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' cannot be longer than '32' characters (Service : ElasticLoadBalancingV2, Status Code: 400, Request id: xxxxxxxxxx)

CFN lint not reporting that load balancers names cannot be longer than 32 characters and hence fails during the actual CFN execution.

As indicated here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-elasticloadbalancingv2-loadbalancer.html#cfn-elasticloadbalancingv2-loadbalancer-name
Name
The name of the load balancer. This name must be unique per region per account, can have a maximum of 32 characters, must contain only alphanumeric characters or hyphens, must not begin or end with a hyphen, and must not begin with "internal-".

### Describe the solution you'd like

Update CFN Lint to report "Error" if the load balancer name is longer than 32 characters

### Additional context

No workaround. It is one of the top occurring common issues when provisioning an Load balancer

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
I think this pattern should handle all the scenarios.   `^(?!internal-)[a-zA-Z0-9](-?[a-zA-Z0-9]){0,30}$`

**Comment by kddejong** [comment]
Fixed in v0 and v1
