### ISSUE TITLE
AWS::Lambda::Function VpcConfig : Members must satisfy regular expression pattern: ^sg-[0-9a-zA-Z]*$] in vpcConfig.securityGroupIds

### ISSUE THREAD

**Issue by johnanand707** [aws-cloudformation/cfn-lint#3261]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

CFT template fails with the below error message if security group id doesn't match the regular expression pattern ^sg-[0-9a-zA-Z]*$] in AWS::Lambda::Function VpcConfig.securityGroupIds

CREATE_FAILED: Resource handler returned message: Validation error detected: Value '<<Security Group Names>>' at 'vpcConfig.securityGroupIds' failed to satisfy constraint: Member must satisfy constraint: [Member must have length less than or equal to 102, Member must have length greater than or equal to 0, Members must satisfy regular expression pattern: ^sg-[0-9a-zA-Z]*$] (Service : Lambda, Status Code: 400)

Developers tend to provide security group names instead of security group ids which results in failure during CFN execution as it doesn't match the expected regex pattern

### Describe the solution you'd like

Update CFN Lint to validate and report it as "Error" if the SG provided doesn't matches regex ^sg-[0-9a-zA-Z]*$].

### Additional context

No work around.  It is one of the top occurring common issues when provisioning a Lambda function.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Please keep submitting these types of requests.  I will work as quick as I can to fix them.  Thank you!

**Comment by kddejong** [comment]
I've been doing some work on this for v1.  I'm going to start tagging security group properties with `format` of `AWS::EC2::SecurityGroup.GroupId` this will allow me to more uniformly apply the pattern instead of having it copied it everywhere.  The interesting bit here is I have found 4-5 patterns some that allow upper case, some that don't, etc.

**Comment by kddejong** [comment]
This is fixed in v1 and v0.
