### ISSUE TITLE
Add cfn-lint to CloudFormation SDK

### ISSUE THREAD

**Issue by bildungsroman** [aws-cloudformation/cfn-lint#3387]
### Is this feature request related to a new rule or cfn-lint capabilities?

New capability

### Describe the feature you'd like to request

Currently, the CloudFormation SDK has a [ValidateTemplateCommand](https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/cloudformation/command/ValidateTemplateCommand/) that is ...pretty useless as a validator. It would be amazing to have that command run cfn-lint as return the results instead.

### Describe the solution you'd like

Have the ValidateTemplateCommand return the results of running cfn-lint on a template.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [X] ⚠️ This feature might incur a breaking change

**Comment by isuftin** [comment]
Also, being that AWS SDK does come in a Python flavor, the Python version could pick up cfn-lint libs directly instead of needing to run the commandline binary like I assume non-Python SDKs would

**Comment by bildungsroman** [comment]
@isuftin Sure, I can create an issue there

**Comment by bildungsroman** [comment]
Issue created in case someone finds this in the future: https://github.com/aws/aws-sdk-js-v3/issues/6491
