### ISSUE TITLE
cfn-lint gives an error output even if check empty yaml file

### ISSUE THREAD

**Issue by ThomasDDY** [aws-cloudformation/cfn-lint#3573]
### CloudFormation Lint Version

1.9.5

### What operating system are you using?

AWS Linux

### Describe the bug

The new version of cfn-lint gives an error message even if checking the empty yaml file.
The last working version is 0.87.4. Any versions newer than 0.87.4 give the same error message. 
Here is the output. 

(venv) [root@ip-10-188-193-11 ~]# cfn-lint --version
cfn-lint 1.9.5
(venv) [root@ip-10-188-193-11 ~]# vi test.yaml
(venv) [root@ip-10-188-193-11 ~]# ls
test.yaml  venv
(venv) [root@ip-10-188-193-11 ~]# cat test.yaml
# test purpose
(venv) [root@ip-10-188-193-11 ~]# cfn-lint -t test.yaml
E0002 Unknown exception while processing rule E1001: "'dict' object has no attribute 'start_mark'"
test.yaml:1:1

### Expected behavior

Fix the bug

### Reproduction template

(venv) [root@ip-10-188-193-11 ~]# cfn-lint --version
cfn-lint 1.9.5
(venv) [root@ip-10-188-193-11 ~]# vi test.yaml
(venv) [root@ip-10-188-193-11 ~]# ls
test.yaml  venv
(venv) [root@ip-10-188-193-11 ~]# cat test.yaml
# test purpose
(venv) [root@ip-10-188-193-11 ~]# cfn-lint -t test.yaml
E0002 Unknown exception while processing rule E1001: "'dict' object has no attribute 'start_mark'"
test.yaml:1:1

**Comment by ThomasDDY** [comment]
I still got the error.

(venv) [root@ip-10-188-224-84 ~]# cfn-lint --version
cfn-lint 1.9.5
(venv) [root@ip-10-188-224-84 ~]# vi test.yaml
(venv) [root@ip-10-188-224-84 ~]# cfn-lint -t test.yaml
E0002 Unknown exception while processing rule E1001: "'dict' object has no attribute 'start_mark'"
test.yaml:1:1

(venv) [root@ip-10-188-224-84 ~]# cat test.yaml
# test purpose

**Comment by kddejong** [comment]
Fix is in main but not released. We've been releasing fairly frequently so shouldn't be much longer

**Comment by ThomasDDY** [comment]
@kddejong 
1.10.1 version gives another error for empty yaml file.

(venv) [root@ip-10-188-193-12 ~]# cfn-lint --version
cfn-lint 1.10.1
(venv) [root@ip-10-188-193-12 ~]# vi test.yaml
(venv) [root@ip-10-188-193-12 ~]# cat test.yaml
# test purpose
(venv) [root@ip-10-188-193-12 ~]# cfn-lint -t test.yaml
E1001 'Resources' is a required property
test.yaml:1:1

**Comment by GZLiew** [comment]
yes we are getting the error as well even with a defined json file with properties
