### ISSUE TITLE
E3693 - PerformanceInsightsEnabled not recognised as valid attribute for DB Cluster

### ISSUE THREAD

**Issue by armanjal** [aws-cloudformation/cfn-lint#3693]
### CloudFormation Lint Version

1.14.0 and 1.12.4

### What operating system are you using?

Mac

### Describe the bug

E3693 Additional properties are not allowed 'PerformanceInsightsEnabled' when creating Aurora cluster

### Expected behavior

Cloudformation allows PerformanceInsightsEnabled as a property and does actually make the expected changes when deployed. Cfn-lint should allow this property to be added in a DB cluster. [See docs here.](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-rds-dbcluster.html#cfn-rds-dbcluster-performanceinsightsenabled:~:text=%3A%20No%20interruption-,PerformanceInsightsEnabled,-Specifies%20whether%20to)

### Reproduction template

Dbcluster with PerformanceInsightsEnabled in the block

**Comment by kddejong** [comment]
This rule is related to `Valid for Cluster Type: Multi-AZ DB clusters only` in the docs.  This is a capability of aurora clusters too so the docs may be off.  Going to test it out and double validate.

**Comment by kddejong** [comment]
One last thing.  [Aurora Serverless v1](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Concepts.Aurora_Fea_Regions_DB-eng.Feature.PerfInsights.html) doesn't support this property.  This is a totally configurable option for Aurora Serverless v2.  

Going to move this to a new Warning rule that will only alert when using Auro Serverless v1

**Comment by armanjal** [comment]
Many thanks for the fast turnaround! 
I should have mentioned that I'm using a Multi-AZ, Aurora Serverless V2 instances cluster
