### ISSUE TITLE
Add a rule to avoid non-strings in template outputs

### ISSUE THREAD

**Issue by francipvb** [aws-cloudformation/cfn-lint#3725]
### Describe the feature you'd like to request

Recently I had an issue deploying to cloudformation and I found that the issue was an exported number value.

Therefore I suggest you to add a lint rule to check output values for references to numbered values (just for references to resource attributes).

### Describe the solution you'd like

I assume the linter have access to the JSON schema definition and the solution should be a matter of reference solving and checking.

I think a check for the `GetAtt` function should be enough.

### Additional context

I was trying to deploy a MemoryDB cluster and a sibling stack was referencing the cluster port. I'm using the CDK.

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
Agreed.  Looking into this.  I thought we had covered this but I need to clean some of the logic up.  Turns out if you do `Value: 1` that it works but if you do `Value: !Gett Resource.NonStringProperty` it will fail.  

Its bringing up that this issue extends beyond just Output Value and also exists in Sub, Joins, etc.

**Comment by Dantemss** [comment]
@kddejong after this change, it's not clear to me how we're supposed to Output for example an RDS DBCluster's Port, which is a number.

`Value: !GetAtt DBCluster.Port` fails with E6101
Attempting to cast it with something like `Value: !Sub ${DBCluster.Port}` also fails with E6101

Unless that is something that changed very recently, CloudFormation used to happily accept `Value: !GetAtt DBCluster.Port`

**Comment by kddejong** [comment]
@Dantemss and this is to a `AWS::RDS::DBCluster`?   And are you using `Endpoint.Port`? or `.Port`?

**Comment by Dantemss** [comment]
@kddejong sorry, my mistake. Our case is actually an `AWS::DocDb::DBCluster`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html
