### ISSUE TITLE
!GetAtt DocDB::Cluster.Port is reporting as an integer

### ISSUE THREAD

**Issue by kddejong** [aws-cloudformation/cfn-lint#3757]
@kddejong after this change, it's not clear to me how we're supposed to Output for example an RDS DBCluster's Port, which is a number.

`Value: !GetAtt DBCluster.Port` fails with E6101
Attempting to cast it with something like `Value: !Sub ${DBCluster.Port}` also fails with E6101

Unless that is something that changed very recently, CloudFormation used to happily accept `Value: !GetAtt DBCluster.Port`

_Originally posted by @Dantemss in https://github.com/aws-cloudformation/cfn-lint/issues/3725#issuecomment-2419900363_

**Comment by Dantemss** [comment]
My mistake, this is an `AWS::DocDb::DBCluster`: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-docdb-dbcluster.html

**Comment by kddejong** [comment]
This property is an exception.  We currently assume that the type for these exceptions matches to the schema definition but that isn't true in this case.  Working on a fix.
