### ISSUE TITLE
Enhance E1011 Message ( is too long)

### ISSUE THREAD

**Issue by namireddy** [aws-cloudformation/cfn-lint#3782]
### Is this feature request related to a new rule or cfn-lint capabilities?

rules

### Describe the feature you'd like to request

Fn::FindInMap, When the nested level depth is greater than 2 , error E1011 is thrown with a message xxx is too long (3). 
Sample:
Mappings:
  MyCustomMap
     Level1:
        Level2:
           "key":"value"

Error message when cfn-lint is run
E1011  ['MyCustomMap',  'Level1',  'Level2',' Key'] is too long (3)
E3024 ['MyCustomMap', 'Level1',  'Level2', 'Key'] is too long (3)

### Describe the solution you'd like

Can the message be improved, to say "FindInMap only supports up to two levels of nesting for map lookups"

### Is this something that you'd be interested in working on?

- [ ] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by kddejong** [comment]
This is the result of the `maxItems` keyword https://github.com/aws-cloudformation/cfn-lint/blob/8164ed9d02841d7c7989e7a5691ae515f48e9fe4/src/cfnlint/jsonschema/_keywords.py#L322-L326

We can alter the wording inside functions or alter the wording for any occurrences of `maxItems`.  The error message from the service would look like `expected maximum item count: 3, found: 4`.  Then we could add a function prefix like `Fn::FindInMap expected maximum item count: 3, found: 4`
