### ISSUE TITLE
Can't run in Travis CI xenial

### ISSUE THREAD

**Issue by alexjurkiewicz** [aws-cloudformation/cfn-lint#471]
I was testing the new Travis CI image:

https://blog.travis-ci.com/2018-11-08-xenial-release
https://docs.travis-ci.com/user/reference/xenial/

My install script ran `pip install --user --upgrade cfn-lint` and then `cfn-lint my.cfn.yaml` which gave this error:

```Traceback (most recent call last):
  File "/home/travis/.local/bin/cfn-lint", line 7, in <module>
    from cfnlint.__main__ import main
  File "/home/travis/.local/lib/python2.7/site-packages/cfnlint/__main__.py", line 19, in <module>
    import cfnlint.core
  File "/home/travis/.local/lib/python2.7/site-packages/cfnlint/core.py", line 24, in <module>
    import cfnlint.maintenance
  File "/home/travis/.local/lib/python2.7/site-packages/cfnlint/maintenance.py", line 19, in <module>
    import requests
  File "/usr/lib/python2.7/dist-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/usr/lib/python2.7/dist-packages/requests/utils.py", line 25, in <module>
    from . import certs
ImportError: cannot import name certs
```

I "fixed" this problem by just changing to Python3 in my build script:

```
pyenv global 3.7
pip3 install --user --upgrade cfn-lint
cfn-lint stack.cfn.yaml
```

But there might be some other lingering issue here

**Comment by kddejong** [comment]
Thanks.  I'll have to check this out.  I just tried a standard xenial container and things went well.   Let me do some more digging...

**Comment by kddejong** [comment]
I was able to reproduce this with and running `sudo pip install cfn-lint` and the following in my .travisci file
```
sudo: true
dist: xenial
```

**Comment by alexjurkiewicz** [comment]
Yup. The Sudo true is a noop now btw

**Comment by kddejong** [comment]
@alexjurkiewicz are you using sudo in your pip install commands for cfn-lint?  Or installing with `--user`?

**Comment by alexjurkiewicz** [comment]
Latter

**Comment by kddejong** [comment]
I believe earlier versions of `requests` is causing this issue.  Looks like the built in python on the containers for Travis have ~2.9.1.  We will require a newer version.  Testing I found this to be at least 2.15.
